version: "3"

services:
  aviation-hackathon-sf:
    build:
      context: .
      dockerfile: Dockerfile.basic
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
    volumes:
      - ./sr20.md:/app/sr20.md:ro
      - ./checklist_before_takeoff.json:/app/checklist_before_takeoff.json
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server --include /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
